#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

run_node_test <<'JS'
const model = requireFromRoot('Model.js')
const fixture = readFromRoot('test/fixtures/status.json')

// ---- reading the snapshot
const snap = model.parseSnapshot(fixture)
assertEqual(snap.ok, true, 'model reads the engine snapshot')
assertEqual(snap.docker.available, true, 'model reads docker availability')
assertEqual(snap.docker.context, 'default', 'model reads the docker context name')
assertEqual(snap.projects.length, 3, 'model lifts every project')
assertDeepEqual(snap.counts, { total: 3, running: 1, starting: 0, attention: 1, stopped: 1 }, 'model counts projects by state')

const [storefront, billing, docs] = snap.projects
assertEqual(storefront.status, 'running', 'model keeps a running project running')
assertEqual(storefront.servicesRunning, 3, 'model counts running services')
assertEqual(storefront.servicesTotal, 3, 'model counts declared services')
assertEqual(storefront.branch, 'main', 'model reads the git branch')
assertEqual(storefront.dirty, true, 'model reads the dirty flag')
assertEqual(storefront.workspace, 'Acme', 'model resolves workspace membership by project id')
assertEqual(storefront.localDomain, 'storefront.test', 'model reads the local https domain')
assertEqual(billing.status, 'degraded', 'model keeps a degraded project degraded')
assertEqual(billing.servicesRunning, 2, 'model does not count an absent container as running')
assertDeepEqual(billing.unhealthy, ['queue'], 'model names unhealthy services')
assertEqual(docs.status, 'stopped', 'model keeps a stopped project stopped')
assertEqual(docs.branch, '', 'model blanks a null branch')
assertEqual(docs.workspace, '', 'model leaves a project outside every workspace unlabelled')

// ---- tolerance: the widget must never throw on what the CLI prints
assertEqual(model.parseSnapshot('').ok, false, 'model refuses empty output')
assertEqual(model.parseSnapshot('not json').ok, false, 'model refuses non-JSON output')
assertEqual(model.parseSnapshot('[]').ok, false, 'model refuses a non-object document')
const bare = model.parseSnapshot('{}')
assertEqual(bare.ok, true, 'model accepts a document with nothing in it')
assertEqual(bare.docker.available, false, 'model treats missing docker as unavailable')
assertDeepEqual(bare.counts, { total: 0, running: 0, starting: 0, attention: 0, stopped: 0 }, 'model counts nothing as nothing')
const odd = model.parseSnapshot(JSON.stringify({ projects: [null, 7, { id: 'x', status: 'weird' }, { name: '' }] }))
assertEqual(odd.projects.length, 1, 'model skips entries that are not projects')
assertEqual(odd.projects[0].status, 'stopped', 'model treats an unknown status as stopped')
assertEqual(odd.projects[0].name, 'x', 'model falls back to the id when the name is missing')

// ---- finding a project the way the CLI does
assertEqual(model.findProject(snap.projects, 'billing-api').name, 'billing-api', 'model finds a project by name')
assertEqual(model.findProject(snap.projects, 'p-docs').name, 'docs', 'model finds a project by id')
assertEqual(model.findProject(snap.projects, 'code/storefront').name, 'storefront', 'model finds a project by path suffix')
assertEqual(model.findProject(snap.projects, 'nope'), null, 'model returns null for an unknown project')
assertEqual(model.findProject(snap.projects, ''), null, 'model returns null for an empty query')

// ---- the widget's one word
assertEqual(model.widgetState('ready', snap), 'attention', 'a degraded project puts the widget in attention')
const calm = model.parseSnapshot(JSON.stringify({ docker: { available: true }, projects: [{ id: 'a', name: 'a', status: 'running' }] }))
assertEqual(model.widgetState('ready', calm), 'running', 'a running project puts the widget in running')
const quiet = model.parseSnapshot(JSON.stringify({ docker: { available: true }, projects: [{ id: 'a', name: 'a', status: 'stopped' }] }))
assertEqual(model.widgetState('ready', quiet), 'idle', 'only stopped projects put the widget in idle')
const down = model.parseSnapshot(JSON.stringify({ docker: { available: false, reason: 'notRunning' }, projects: [] }))
assertEqual(model.widgetState('ready', down), 'docker-down', 'unreachable docker outranks project counts')
assertEqual(model.widgetState('missing', snap), 'missing', 'a missing CLI outranks everything')
assertEqual(model.widgetState('too-old', snap), 'outdated', 'a CLI without --json is outdated')
assertEqual(model.widgetState('checking', snap), 'checking', 'the first poll is checking')
assertEqual(model.widgetState('', snap), 'checking', 'an unset phase is checking')
assertEqual(model.widgetState('ready', model.emptySnapshot()), 'error', 'ready without an answer is an error')

// ---- what the bar shows
assertEqual(model.barLabel(snap.counts, 'ratio', 'attention'), '1/3', 'bar label shows running over total')
assertEqual(model.barLabel(snap.counts, 'running', 'attention'), '1', 'bar label can show only the running count')
assertEqual(model.barLabel(snap.counts, 'none', 'attention'), '', 'bar label can be switched off')
assertEqual(model.barLabel(snap.counts, 'ratio', 'missing'), '', 'bar label is empty without a CLI')
assertEqual(model.barLabel(snap.counts, 'ratio', 'docker-down'), '', 'bar label is empty without docker')
assertEqual(model.barLabel(quiet.counts, 'ratio', 'idle'), '0/1', 'bar label still counts stopped projects')
assertEqual(model.iconColorRole('attention'), 'urgent', 'attention paints the mark urgent')
assertEqual(model.iconColorRole('running'), 'foreground', 'running paints the mark in the foreground')
assert(model.iconOpacity('running') > model.iconOpacity('idle'), 'running is brighter than idle')
assert(model.iconOpacity('idle') > model.iconOpacity('missing'), 'idle is brighter than missing')
assertEqual(model.tooltipText('attention', snap.counts), 'Mast · 1 of 3 projects running, 1 needs attention', 'tooltip reads the counts as a sentence')
assertEqual(model.tooltipText('running', { total: 1, running: 1, starting: 0, attention: 0, stopped: 0 }), 'Mast · 1 of 1 project running', 'tooltip uses the singular for one project')
assertEqual(model.tooltipText('missing', snap.counts), 'Mast CLI not found — get it from mast.sh', 'tooltip says where to get the CLI')
assertEqual(model.tooltipText('docker-down', snap.counts), 'Mast · Docker unavailable', 'tooltip says when docker is down')

// ---- what the panel shows
assertEqual(model.heroMeta('attention', snap), '1 of 3 projects running, 1 needs attention', 'hero meta reads the counts')
assertEqual(model.heroMeta('docker-down', down), 'Docker not running', 'hero meta names the docker problem')
assertEqual(model.heroMeta('missing', snap), 'CLI not found', 'hero meta says the CLI is missing')
assertEqual(model.heroDetail('attention', snap.counts), '1/3', 'hero pill shows the ratio')
assertEqual(model.heroDetail('missing', snap.counts), '', 'hero pill is empty without a CLI')
assertEqual(model.heroDetail('idle', { total: 0, running: 0, starting: 0, attention: 0, stopped: 0 }), '', 'hero pill is empty with no projects')
assertEqual(model.guidance('attention', snap, '').title, '', 'no guidance card while the list can show')
assertEqual(model.guidance('missing', snap, '').title, 'Mast CLI not found', 'guidance names a missing CLI')
assertEqual(model.guidance('outdated', snap, '').title, 'Mast CLI needs updating', 'guidance names an outdated CLI')
assertEqual(model.guidance('error', snap, 'boom').hint, 'boom', 'guidance repeats the last error')
assertEqual(model.guidance('docker-down', down, '').title, 'Docker is not running', 'guidance names the docker problem')
assertEqual(model.dockerReasonPhrase('permissionDenied'), 'permission denied', 'docker reasons read as words')
assertEqual(model.dockerReasonPhrase('somethingNew'), 'unavailable', 'unknown docker reasons fall back')
assertEqual(model.projectMeta(storefront), 'Running · 3/3 services · main* · Acme', 'project meta lists state, services, branch and workspace')
assertEqual(model.projectMeta(docs), 'Stopped · 0/1 service', 'project meta uses the singular and skips what is missing')
assertEqual(model.projectNote(billing), 'Unhealthy: queue', 'project note names unhealthy services before warnings')
assertEqual(model.projectNote(docs), '', 'project note is empty when nothing is wrong')
assertEqual(model.projectNote({ resolutionError: 'compose.yaml missing', unhealthy: ['x'], warnings: [] }), 'compose.yaml missing', 'project note puts a resolution error first')
assertEqual(model.projectNote({ resolutionError: '', unhealthy: [], warnings: ['No .env file'] }), 'No .env file', 'project note falls back to the first warning')
assertEqual(model.statusRole('failed'), 'urgent', 'failed is urgent')
assertEqual(model.statusRole('starting'), 'foreground', 'starting is foreground')
assertEqual(model.statusRole('stopped'), 'dim', 'stopped is dim')

// ---- intent into commands
assertEqual(model.primaryAction(storefront), 'stop', 'the primary verb on a running project is stop')
assertEqual(model.primaryAction(billing), 'stop', 'the primary verb on a degraded project is stop')
assertEqual(model.primaryAction(docs), 'start', 'the primary verb on a stopped project is start')
assertEqual(model.primaryAction({ status: 'failed' }), 'start', 'the primary verb on a failed project is start')
assertEqual(model.primaryAction(null), 'start', 'the primary verb without a project is start')
assertEqual(model.canRestart(storefront), true, 'a running project can restart')
assertEqual(model.canRestart(docs), false, 'a stopped project has nothing to restart')
assertEqual(model.actionLabel('stop'), 'Stop', 'verbs are capitalised for buttons')
assertDeepEqual(model.statusArgv('/home/dev/.local/bin/mast'), ['/home/dev/.local/bin/mast', 'status', '--json'], 'status is one argv vector')
assertDeepEqual(model.mastArgv('mast', 'restart', 'billing-api'), ['mast', 'restart', 'billing-api'], 'verbs are one argv vector')
assertEqual(model.browserUrl(storefront), 'https://storefront.test', 'the trusted local domain wins over APP_URL')
assertEqual(model.browserUrl(billing), 'http://localhost:8081', 'APP_URL is used without a local domain')
assertEqual(model.browserUrl(docs), '', 'no address means no browser button')
assertEqual(model.deepLink({ name: 'billing api' }), 'mast://project/billing%20api', 'deep links encode the project name')
assertEqual(model.APP_LINK, 'mast://', 'the bare app link is the scheme alone')

// ---- reading the CLI's failures
const tooOld = model.classifyStatusFailure(2, '', "error: unexpected argument '--json' found\n\nUsage: mast status")
assertEqual(tooOld.kind, 'too-old', 'an unknown --json flag means an old CLI')
const engine = model.classifyStatusFailure(2, '', 'cannot read engine state: connection refused\n')
assertEqual(engine.kind, 'error', 'other failures are errors')
assertEqual(engine.message, 'cannot read engine state: connection refused', 'the last line the CLI printed is the message')
assertEqual(model.classifyStatusFailure(1, '', '').message, 'mast status failed (exit 1)', 'a silent failure still says something')
assertEqual(model.actionSummary('start', 'docs', 0, 'ok', '').message, 'docs: start completed', 'a successful verb is reported as completed')
const failed = model.actionSummary('start', 'docs', 1, 'pulling…\n', 'docs: port 8080 is taken\n')
assertEqual(failed.ok, false, 'a failed verb is reported as failed')
assertEqual(failed.message, 'docs: start failed — port 8080 is taken', 'a failed verb carries the last line the CLI printed, without repeating the name')
const plain = model.actionSummary('stop', 'docs', 1, '', 'connection refused\n')
assertEqual(plain.message, 'docs: stop failed — connection refused', 'a failure line without the name is kept whole')
assertEqual(model.actionSummary('stop', 'docs', 1, '', '').message, 'docs: stop failed', 'a silent failure still names the verb')
assertEqual(model.lastLine('a\n\n b \n\n'), 'b', 'last line skips blank lines and trims')
assertEqual(model.elide('x'.repeat(200), 20).length, 20, 'elide caps at the limit')

// ---- the optional desktop app
assert(model.keyHints(true).indexOf('m mast') !== -1, 'key hints mention the app when a handler exists')
assert(model.keyHints(false).indexOf('m mast') === -1, 'key hints drop the app when nothing handles mast:// links')
assertEqual(model.appAvailableFromProbe('MAST_APP=/usr/bin/mast-desktop\n'), true, 'a desktop binary on PATH makes the app available')
assertEqual(model.appAvailableFromProbe('Welcome!\nMAST_APP=/home/u/.local/share/applications/mast.desktop\n'), true, 'a registered handler makes the app available, banner or not')
assertEqual(model.appAvailableFromProbe('MAST_APP=\n'), false, 'no binary and no handler means no app')
assertEqual(model.appAvailableFromProbe('some banner text\n'), false, 'output without the marker never counts as a handler')
assertEqual(model.appAvailableFromProbe(''), false, 'empty output means no app')
assertEqual(model.appProbeArgv()[0], 'bash', 'the probe runs through a login shell so PATH matches the profile')
assertEqual(model.appLauncherFromProbe('MAST_APP=/home/u/Downloads/Mast_0.7.1_amd64.AppImage\n'), '/home/u/Downloads/Mast_0.7.1_amd64.AppImage', 'the launcher path is lifted off the marker line')
assertDeepEqual(model.appLaunchArgv('/opt/mast/mast-desktop', 'mast://project/a%20b'), ['bash', '-lc', 'exec "$1" "$2"', 'omarchy-mast', '/opt/mast/mast-desktop', 'mast://project/a%20b'], 'links go straight to the launcher as argv, never through xdg-open')
assert(model.appProbeArgv()[2].indexOf('command -v "$e"') !== -1, 'a handler only counts when its launcher still exists')
assert(model.appProbeArgv()[2].indexOf('*[Mm]ast*') !== -1, 'a handler only counts when its launcher is Mast')

// ---- timing
assertEqual(model.refreshIntervalMs(30, false), 30000, 'closed panels poll at the configured interval')
assertEqual(model.refreshIntervalMs(30, true), 10000, 'open panels poll faster')
assertEqual(model.refreshIntervalMs(5, true), 5000, 'open panels never poll slower than configured')
assertEqual(model.refreshIntervalMs('nonsense', false), 30000, 'a bad interval falls back to the default')
assertEqual(model.refreshIntervalMs(1, false), 5000, 'the interval has a floor')
assertEqual(model.refreshIntervalMs(99999, false), 3600000, 'the interval has a ceiling')
JS
